language: java

jdk:
  - oraclejdk8

script:
  - mvn clean package
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://discordapp.com/api/webhooks/366241626290520064/XVYVfvXiBsotqmykyKYbFGy2NNylnzAnLxlnGNN_T91hTR4ML6iRA5MQDQAt3mURq-_g
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always