ignore:
  - "src/main/java/org/apache/maven/App.java"

coverage:
  range: 30..75

  status:
    project: off
    
    patch:
      default:
        paths:
          - "src/main/java/org/apache/maven/Maths.java"